<a href="https://colab.research.google.com/github/IsagiYoichi640/SQL-Statement/blob/main/Play_with_tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
file = files.upload()

Saving database.sqlite to database.sqlite

In [2]:
import sqlite3
database = 'database.sqlite'
conn = sqlite3.connect(database)
print('Opened data successfully')

Opened data successfully

In [3]:
import pandas as pd
teams = pd.read_sql("""SELECT * FROM TEAM;""",conn)
teams

    Team_Id                    Team_Name
0         1        Kolkata Knight Riders
1         2  Royal Challengers Bangalore
2         3          Chennai Super Kings
3         4              Kings XI Punjab
4         5             Rajasthan Royals
5         6             Delhi Daredevils
6         7               Mumbai Indians
7         8              Deccan Chargers
8         9         Kochi Tuskers Kerala
9        10                Pune Warriors
10       11          Sunrisers Hyderabad
11       12      Rising Pune Supergiants
12       13                Gujarat Lions

In [4]:
matches = pd.read_sql("""SELECT * FROM Match;""",conn)
matches

,Match_Id,Team_1,Team_2,Match_Date,Season_Id,Venue_Id,Toss_Winner,Toss_Decide,Win_Type,Win_Margin,Outcome_type,Match_Winner,Man_of_the_Match
0,335987,2,1,2008-04-18 00:00:00,1,1,2,1,1,140.0,1,1.0,2.0
1,335988,4,3,2008-04-19 00:00:00,1,2,3,2,1,33.0,1,3.0,19.0
2,335989,6,5,2008-04-19 00:00:00,1,3,5,2,2,9.0,1,6.0,90.0
3,335990,7,2,2008-04-20 00:00:00,1,4,7,2,2,5.0,1,2.0,11.0
4,335991,1,8,2008-04-20 00:00:00,1,5,8,2,2,5.0,1,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,981016,6,2,2016-05-22 00:00:00,9,27,2,1,2,6.0,1,2.0,8.0
573,981018,13,2,2016-05-24 00:00:00,9,1,2,1,2,4.0,1,2.0,110.0
574,981020,11,1,2016-05-25 00:00:00,9,3,1,1,1,22.0,1,11.0,163.0
575,981022,13,11,2016-05-27 00:00:00,9,3,11,1,2,4.0,1,11.0,187.0
576,981024,2,11,2016-05-29 00:00:00,9,1,11,2,1,8.0,1,11.0,385.0

In [5]:
DD = pd.read_sql("""SELECT * FROM Match WHERE Match_Winner == 6;""", conn)
DD

,Match_Id,Team_1,Team_2,Match_Date,Season_Id,Venue_Id,Toss_Winner,Toss_Decide,Win_Type,Win_Margin,Outcome_type,Match_Winner,Man_of_the_Match
0,335989,6,5,2008-04-19 00:00:00,1,3,5,2,2,9,1,6,90
1,335993,8,6,2008-04-22 00:00:00,1,7,8,2,2,9,1,6,41
2,336003,6,2,2008-04-30 00:00:00,1,3,2,1,1,10,1,6,118
3,336006,3,6,2008-05-02 00:00:00,1,8,3,2,2,8,1,6,41
4,336025,6,8,2008-05-15 00:00:00,1,3,8,1,1,12,1,6,136
5,336031,2,6,2008-05-19 00:00:00,1,1,6,1,2,5,1,6,132
6,336037,6,7,2008-05-24 00:00:00,1,3,6,1,2,5,1,6,88
7,392188,6,4,2009-04-19 00:00:00,2,10,6,1,2,10,1,6,175
8,392194,3,6,2009-04-23 00:00:00,2,12,6,2,1,9,1,6,110
9,392199,2,6,2009-04-26 00:00:00,2,11,2,2,2,6,1,6,135
10,392206,8,6,2009-04-30 00:00:00,2,13,6,1,2,6,1,6,223
11,392216,6,1,2009-05-05 00:00:00,2,12,1,2,2,9,1,6,40
12,392220,6,7,2009-05-08 00:00:00,2,14,7,2,2,7,1,6,73
13,392224,6,1,2009-05-10 00:00:00,2,15,6,1,2,7,1,6,136
14,392228,8,6,2009-05-13 00:00:00,2,12,8,1,1,12,1,6,89
15,392235,6,5,2009-05-17 00:00:00,2,17,6,2,1,14,1,6,110
16,392240,6,7,2009-05-21 00:00:00,2,13,6,1,2,4,1,6,41
17,419113,4,6,2010-03-13 00:00:00,3,2,6,1,2,5,1,6,40
18,419116,5,6,2010-03-15 00:00:00,3,19,6,1,2,6,1,6,41
19,419133,2,6,2010-03-25 00:00:00,3,1,2,1,1,17,1,6,237
20,419136,6,1,2010-03-29 00:00:00,3,3,6,2,1,40,1,6,187
21,419139,6,5,2010-03-31 00:00:00,3,3,6,2,1,67,1,6,88
22,419145,6,2,2010-04-04 00:00:00,3,3,6,2,1,37,1,6,241
23,419160,3,6,2010-04-15 00:00:00,3,8,3,2,2,6,1,6,40
24,501218,10,6,2011-04-17 00:00:00,4,9,6,1,2,3,1,6,27
25,501228,6,4,2011-04-23 00:00:00,4,3,4,1,1,29,1,6,187
26,501238,9,6,2011-04-30 00:00:00,4,23,6,2,1,38,1,6,41
27,501248,8,6,2011-05-05 00:00:00,4,7,6,1,2,4,1,6,41
28,548312,1,6,2012-04-05 00:00:00,5,5,6,1,2,8,1,6,29
29,548321,6,3,2012-04-10 00:00:00,5,3,6,1,2,8,1,6,190
30,548326,6,8,2012-04-19 00:00:00,5,3,8,2,2,5,1,6,158
31,548330,7,6,2012-04-16 00:00:00,5,4,6,1,2,7,1,6,293
32,548334,8,6,2012-05-10 00:00:00,5,7,8,2,2,9,1,6,187
33,548342,10,6,2012-04-24 00:00:00,5,26,10,2,2,8,1,6,41
34,548347,6,7,2012-04-27 00:00:00,5,3,7,1,1,37,1,6,41
35,548350,6,5,2012-04-29 00:00:00,5,3,6,2,1,1,1,6,41
36,548354,5,6,2012-05-01 00:00:00,5,6,5,2,2,6,1,6,322
37,548374,6,4,2012-05-15 00:00:00,5,3,4,2,2,5,1,6,232
38,548379,4,6,2012-05-19 00:00:00,5,22,6,1,2,6,1,6,232
39,598029,6,7,2013-04-21 00:00:00,6,3,7,2,2,9,1,6,41
40,598040,6,10,2013-04-28 00:00:00,6,27,10,1,1,15,1,6,187
41,598045,6,1,2013-05-01 00:00:00,6,27,1,2,2,7,1,6,187
42,729294,1,6,2014-04-19 00:00:00,7,31,1,2,2,4,1,6,154
43,729314,6,7,2014-04-27 00:00:00,7,30,7,2,2,6,1,6,185
44,829730,4,6,2015-04-15 00:00:00,8,32,4,2,2,5,1,6,260
45,829736,11,6,2015-04-18 00:00:00,8,25,6,2,1,4,1,6,154
46,829752,6,7,2015-04-23 00:00:00,8,3,7,1,1,37,1,6,393
47,829772,6,4,2015-05-01 00:00:00,8,3,6,1,2,9,1,6,371
48,829806,6,3,2015-05-12 00:00:00,8,27,3,2,2,6,1,6,15
49,980918,6,4,2016-04-15 00:00:00,9,3,6,1,2,8,1,6,136
50,980926,2,6,2016-04-17 00:00:00,9,1,6,1,2,7,1,6,355
51,980938,6,7,2016-04-23 00:00:00,9,3,7,1,1,10,1,6,351
52,980956,6,1,2016-04-30 00:00:00,9,3,1,1,1,27,1,6,408
53,980966,13,6,2016-05-03 00:00:00,9,34,6,1,2,8,1,6,420
54,980988,11,6,2016-05-12 00:00:00,9,7,6,1,2,7,1,6,350
55,981008,6,11,2016-05-20 00:00:00,9,27,6,1,2,6,1,6,339

In [6]:
DD_S8_S9 = pd.read_sql("""SELECT * FROM Match WHERE Match_Winner == 6 and Season_Id IN (8,9);""", conn)
DD_S8_S9

,Match_Id,Team_1,Team_2,Match_Date,Season_Id,Venue_Id,Toss_Winner,Toss_Decide,Win_Type,Win_Margin,Outcome_type,Match_Winner,Man_of_the_Match
0,829730,4,6,2015-04-15 00:00:00,8,32,4,2,2,5,1,6,260
1,829736,11,6,2015-04-18 00:00:00,8,25,6,2,1,4,1,6,154
2,829752,6,7,2015-04-23 00:00:00,8,3,7,1,1,37,1,6,393
3,829772,6,4,2015-05-01 00:00:00,8,3,6,1,2,9,1,6,371
4,829806,6,3,2015-05-12 00:00:00,8,27,3,2,2,6,1,6,15
5,980918,6,4,2016-04-15 00:00:00,9,3,6,1,2,8,1,6,136
6,980926,2,6,2016-04-17 00:00:00,9,1,6,1,2,7,1,6,355
7,980938,6,7,2016-04-23 00:00:00,9,3,7,1,1,10,1,6,351
8,980956,6,1,2016-04-30 00:00:00,9,3,1,1,1,27,1,6,408
9,980966,13,6,2016-05-03 00:00:00,9,34,6,1,2,8,1,6,420
10,980988,11,6,2016-05-12 00:00:00,9,7,6,1,2,7,1,6,350
11,981008,6,11,2016-05-20 00:00:00,9,27,6,1,2,6,1,6,339

In [7]:
teams.head()

   Team_Id                    Team_Name
0        1        Kolkata Knight Riders
1        2  Royal Challengers Bangalore
2        3          Chennai Super Kings
3        4              Kings XI Punjab
4        5             Rajasthan Royals

In [12]:
result1=pd.read_sql("""SELECT AVG(Win_Margin),Match_Winner FROM Match
WHERE Season_Id==5
 GROUP BY Match_Winner ORDER BY AVG(Win_Margin);""",conn)
result1

   AVG(Win_Margin)  Match_Winner
0         7.625000             4
1         9.090909             6
2         9.400000             7
3        11.250000             8
4        17.833333             1
5        18.375000             2
6        19.250000            10
7        25.100000             3
8        30.285714             5

In [19]:
result2 = pd.read_sql("""SELECT COUNT(DISTINCT Venue_Id)FROM Match
WHERE Season_Id==2;""",conn)
result2

   COUNT(DISTINCT Venue_Id)
0                         8

In [20]:
result3 = pd.read_sql("""SELECT MIN(Win_Margin), MAX(Win_Margin),
               AVG(Win_Margin), COUNT(DISTINCT(Man_of_the_Match))
               FROM Match;""",conn)
result3

,MIN(Win_Margin),MAX(Win_Margin),AVG(Win_Margin),COUNT(DISTINCT(Man_of_the_Match))
0,1,144,17.350352,187

In [24]:
result4 = pd.read_sql("""SELECT SUM(Win_Margin) FROM Match WHERE
 Season_Id==4;""",conn)
result4

   SUM(Win_Margin)
0             1363